//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.bookissues = new HashSet<bookissue>();
        }
    
        public int bid { get; set; }
        public string bname { get; set; }
        public string bgener { get; set; }
        public long bprice { get; set; }
    
        public virtual ICollection<bookissue> bookissues { get; set; }
    }
}
