//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.bookissues = new HashSet<bookissue>();
        }
    
        public int uid { get; set; }
        public string uname { get; set; }
        public long ucontact { get; set; }
        public string uaddress { get; set; }
    
        public virtual ICollection<bookissue> bookissues { get; set; }
    }
}
